// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderManagement.Database.Context;

#nullable disable

namespace OrderManagement.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260406112909_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderManagement.Database.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("City");

                    b.HasIndex("Country");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PostalCode");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("OrderManagement.Database.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "john.smith@gmail.com",
                            FirstName = "John",
                            LastName = "Smith",
                            Password = "JohSmi123!",
                            PhoneNumber = "+1-555-123-4567",
                            Role = 0,
                            RowVersion = new byte[] { 101, 81, 82, 184, 207, 147, 222, 8 }
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Email = "sarah.johnson@yahoo.com",
                            FirstName = "Sarah",
                            LastName = "Johnson",
                            Password = "SarJoh456!",
                            PhoneNumber = "+1-555-234-5678",
                            Role = 0,
                            RowVersion = new byte[] { 70, 89, 82, 184, 207, 147, 222, 8 }
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Email = "michael.brown@hotmail.com",
                            FirstName = "Michael",
                            LastName = "Brown",
                            Password = "MicBro789!",
                            PhoneNumber = "+1-555-345-6789",
                            Role = 0,
                            RowVersion = new byte[] { 85, 89, 82, 184, 207, 147, 222, 8 }
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Email = "emma.davis@outlook.com",
                            FirstName = "Emma",
                            LastName = "Davis",
                            Password = "EmmDav101!",
                            PhoneNumber = "+1-555-456-7890",
                            Role = 0,
                            RowVersion = new byte[] { 91, 89, 82, 184, 207, 147, 222, 8 }
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Email = "david.wilson@protonmail.com",
                            FirstName = "David",
                            LastName = "Wilson",
                            Password = "DavWil202!",
                            PhoneNumber = "+1-555-567-8901",
                            Role = 0,
                            RowVersion = new byte[] { 97, 89, 82, 184, 207, 147, 222, 8 }
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Email = "jennifer.garcia@icloud.com",
                            FirstName = "Jennifer",
                            LastName = "Garcia",
                            Password = "JenGar303!",
                            PhoneNumber = "+1-555-678-9012",
                            Role = 0,
                            RowVersion = new byte[] { 107, 89, 82, 184, 207, 147, 222, 8 }
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Email = "robert.martinez@aol.com",
                            FirstName = "Robert",
                            LastName = "Martinez",
                            Password = "RobMar404!",
                            PhoneNumber = "+1-555-789-0123",
                            Role = 0,
                            RowVersion = new byte[] { 127, 89, 82, 184, 207, 147, 222, 8 }
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Email = "lisa.anderson@mail.com",
                            FirstName = "Lisa",
                            LastName = "Anderson",
                            Password = "LisAnd505!",
                            PhoneNumber = "+1-555-890-1234",
                            Role = 0,
                            RowVersion = new byte[] { 133, 89, 82, 184, 207, 147, 222, 8 }
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Email = "william.taylor@zoho.com",
                            FirstName = "William",
                            LastName = "Taylor",
                            Password = "WilTay606!",
                            PhoneNumber = "+1-555-901-2345",
                            Role = 0,
                            RowVersion = new byte[] { 138, 89, 82, 184, 207, 147, 222, 8 }
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Email = "jessica.thomas@fastmail.com",
                            FirstName = "Jessica",
                            LastName = "Thomas",
                            Password = "JesTho707!",
                            PhoneNumber = "+1-555-012-3456",
                            Role = 0,
                            RowVersion = new byte[] { 144, 89, 82, 184, 207, 147, 222, 8 }
                        });
                });

            modelBuilder.Entity("OrderManagement.Database.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AdditionalCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BillingCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BillingCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BillingPostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BillingState")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BillingStreet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CustomerContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ShippingCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShippingCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingPostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShippingState")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingStreet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Vat")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerContactNumber");

                    b.HasIndex("CustomerEmail");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderDate");

                    b.HasIndex("OrderStatus");

                    b.HasIndex("TotalAmount");

                    b.ToTable("CustomerOrders", (string)null);
                });

            modelBuilder.Entity("OrderManagement.Database.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Price");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Currency = "USD",
                            Description = "High-performance laptop with M2 Pro chip, 16GB RAM and 512GB SSD.",
                            Name = "MacBook Pro 16\"",
                            Price = 2499.99m,
                            Quantity = 15,
                            RowVersion = new byte[] { 184, 71, 81, 184, 207, 147, 222, 8 }
                        },
                        new
                        {
                            Id = 2,
                            Currency = "USD",
                            Description = "Latest iPhone with A17 Pro chip, titanium design, and advanced camera system.",
                            Name = "iPhone 15 Pro",
                            Price = 999.99m,
                            Quantity = 25,
                            RowVersion = new byte[] { 23, 78, 81, 184, 207, 147, 222, 8 }
                        },
                        new
                        {
                            Id = 3,
                            Currency = "USD",
                            Description = "Industry-leading noise canceling headphones with 30-hour battery life.",
                            Name = "Sony WH-1000XM5",
                            Price = 399.99m,
                            Quantity = 20,
                            RowVersion = new byte[] { 31, 78, 81, 184, 207, 147, 222, 8 }
                        },
                        new
                        {
                            Id = 4,
                            Currency = "USD",
                            Description = "Advanced smartwatch with health monitoring and fitness tracking capabilities.",
                            Name = "Apple Watch Series 9",
                            Price = 399.99m,
                            Quantity = 30,
                            RowVersion = new byte[] { 33, 78, 81, 184, 207, 147, 222, 8 }
                        },
                        new
                        {
                            Id = 5,
                            Currency = "USD",
                            Description = "Powerful tablet with M2 chip, Liquid Retina XDR display, and Apple Pencil support.",
                            Name = "iPad Pro 12.9\"",
                            Price = 1099.99m,
                            Quantity = 18,
                            RowVersion = new byte[] { 34, 78, 81, 184, 207, 147, 222, 8 }
                        },
                        new
                        {
                            Id = 6,
                            Currency = "USD",
                            Description = "Professional 4K monitor with USB-C connectivity and color accuracy certification.",
                            Name = "Dell UltraSharp 27\" 4K Monitor",
                            Price = 649.99m,
                            Quantity = 12,
                            RowVersion = new byte[] { 41, 78, 81, 184, 207, 147, 222, 8 }
                        },
                        new
                        {
                            Id = 7,
                            Currency = "USD",
                            Description = "Wireless mouse with ultra-fast scrolling and customizable buttons for productivity.",
                            Name = "Logitech MX Master 3S",
                            Price = 99.99m,
                            Quantity = 40,
                            RowVersion = new byte[] { 42, 78, 81, 184, 207, 147, 222, 8 }
                        },
                        new
                        {
                            Id = 8,
                            Currency = "USD",
                            Description = "RGB mechanical keyboard with Cherry MX switches and programmable macros.",
                            Name = "Mechanical Gaming Keyboard",
                            Price = 149.99m,
                            Quantity = 35,
                            RowVersion = new byte[] { 43, 78, 81, 184, 207, 147, 222, 8 }
                        },
                        new
                        {
                            Id = 9,
                            Currency = "USD",
                            Description = "360-degree Bluetooth speaker with deep bass and 16-hour battery life.",
                            Name = "Bose SoundLink Revolve+",
                            Price = 299.99m,
                            Quantity = 22,
                            RowVersion = new byte[] { 44, 78, 81, 184, 207, 147, 222, 8 }
                        },
                        new
                        {
                            Id = 10,
                            Currency = "USD",
                            Description = "Full-frame mirrorless camera with 24.2MP sensor and advanced autofocus system.",
                            Name = "Canon EOS R6 Mark II",
                            Price = 2499.99m,
                            Quantity = 8,
                            RowVersion = new byte[] { 46, 78, 81, 184, 207, 147, 222, 8 }
                        });
                });

            modelBuilder.Entity("OrderManagement.Database.Models.PurchasedProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OrderId");

                    b.HasIndex("Price");

                    b.HasIndex("ProductId");

                    b.ToTable("PurchasedProducts", (string)null);
                });

            modelBuilder.Entity("OrderManagement.Database.Models.Address", b =>
                {
                    b.HasOne("OrderManagement.Database.Models.Customer", "CustomerInfo")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerInfo");
                });

            modelBuilder.Entity("OrderManagement.Database.Models.PurchasedProduct", b =>
                {
                    b.HasOne("OrderManagement.Database.Models.Order", "OrderInfo")
                        .WithMany("Products")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderInfo");
                });

            modelBuilder.Entity("OrderManagement.Database.Models.Customer", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("OrderManagement.Database.Models.Order", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
